error
on:
  release:
    types:
    - created

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Publish
      if: success() && startsWith(github.ref, 'refs/tags/')
      run: |
        cd client
        yarn run package
        yarn deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
